### ISSUE TITLE
Relax assertion in get_test_bin_dir since it fails when using `cargo test --release`

### ISSUE THREAD

**Issue by ehiggs** [MichaelMcDonnell/test_bin#1]
As a developer, I want to use `cargo test --release` so that I can run tests that execute quickly. Currently `test_bin` asserts that the integration test binary is in `target/debug/deps`. This does not work when using a release build.

**Comment by MichaelMcDonnell** [comment]
I've release version 0.3.0 on crates.io. Thank you again for your contribution.

**Comment by ehiggs** [comment]
Thanks for the quick release. :bowing_man:
